[mgr]
show_hidden = true
linemode = "size"

[opener]
extract = [
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
  { run = 'ouch d -y %*', desc = "Extract here with ouch", for = "windows" },
]

[preview]
max_width = 1920
max_height = 1080

[tasks]
image_bound = [8192, 4608] # 8K resolution

[plugin]
prepend_fetchers = [
  # Git: https://github.com/yazi-rs/plugins/tree/main/git.yazi
  { url = "*", run = "git", group = "git" },
  { url = "*/", run = "git", group = "git" },
]

prepend_previewers = [
  # DuckDB previewer: https://github.com/wylie102/duckdb.yazi
  # { url = "*.csv", run = "duckdb" },
  # { url = "*.tsv", run = "duckdb" },
  # { url = "*.json", run = "duckdb" },
  # { url = "*.parquet", run = "duckdb" },
  # { url = "*.txt", run = "duckdb" },
  # { url = "*.xlsx", run = "duckdb" },
  # { url = "*.db", run = "duckdb" },
  # { url = "*.duckdb", run = "duckdb" },

  # Ouch: https://github.com/ndtoan96/ouch.yazi
  {
    mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}",
    run = "ouch",
  },
]

#append_previewers = [
#  { url = "*", run = "hexyl" },
#]

prepend_preloaders = [
  # DuckDB previewer: https://github.com/wylie102/duckdb.yazi
  # { url = "*.csv", run = "duckdb", multi = false },  
  # { url = "*.tsv", run = "duckdb", multi = false },  
  # { url = "*.json", run = "duckdb", multi = false },  
  # { url = "*.parquet", run = "duckdb", multi = false },
  # { url = "*.txt", run = "duckdb", multi = false },  
  # { url = "*.xlsx", run = "duckdb", multi = false }
]
